### ISSUE TITLE
Record#taggings association cache is not clearing as expected

### ISSUE THREAD

**Issue by alexdunae** [culturecode/acts_as_taggable#8]
I was having difficulty getting this working on the Rails 6 branch so went back and * think * I've confirmed that it was a bug in Rails 4.x as well.

See https://github.com/culturecode/acts_as_taggable/commit/71274976100ee2524162e9964f710d8ec816ff10

When adding `red` and `metal` via `tags << []` the `reset_scoped_associations` method is called.  However, when calling `record.material_taggings.create!` then `reset_scoped_associations` is not called, resulting in stale tag reads.  It appears the `after_add` callback isn't calling as expected.

AFAIK, this test shouldn't have been passing before.

**Comment by rywall** [comment]
@alexdunae Can you investigate and fix please.

**Comment by alexdunae** [comment]
This was fixed by 3fcbeab
